---
- name: Gather facts for all hosts
  hosts: all
  serial: '{{ serial|default("0") }}'
  gather_facts: false
  tasks:
    - name: collect facts
      setup:
    - name: facts
      set_fact:
        service_ntp_enable: '{{ lookup("env","SERVICE_NTP_ENABLE")| default(False) }}'
        service_rsyslog_enable: '{{ lookup("env","SERVICE_RSYSLOG_ENABLE")| default(False) }}'
        service_tinyproxy_enable: '{{ lookup("env","SERVICE_TINYPROXY_ENABLE")| default(False) }}'
        service_openstack_client_enable: '{{ lookup("env","SERVICE_OPENSTACK_CLIENT_ENABLE")| default(False) }}'
        service_docker_compose_enable: '{{ lookup("env","SERVICE_DOCKER_COMPOSE_ENABLE")| default(False) }}'
        service_docker_enable: '{{ lookup("env","SERVICE_DOCKER_ENABLE")| default(False) }}'
  tags: always

- name: Configure docker hosts
  hosts: docker
  gather_facts: false
  serial: '{{ serial|default("0") }}'
  become: true
  roles:
    - role: ntp
      when: service_ntp_enable

    - role: rsyslog
      when: service_rsyslog_enable

    - role: tinyproxy
      when: service_tinyproxy_enable

    - role: openstack-client
      when: service_openstack_client_enable

    - role: docker-compose
      when: service_docker_compose_enable

    - role: docker
      when: service_docker_enable
