---
- name: Wait for all hosts
  hosts: bastion
  serial: '{{ serial|default("0") }}'
  gather_facts: false
  tasks:
    - name: facts
      set_fact:
        ansible_connection_is_local: '{{ lookup("env","ANSIBLE_CONNECTION")| default(local) }}'

    - name: checking for port open
      wait_for:
        port: 22
        host: "{{ item }}"
        search_regex: OpenSSH
        timeout: 5
      delegate_to: localhost
      with_items: "{{ groups['all'] }}"
      register: port_check
      until: port_check|success
      delay: 1  # Check every 1 seconds. Adjust as you like.
      retries: 120  # Retry up to 120 times. Adjust as needed.
      failed_when: port_check | failed
      when: ansible_connection_is_local != "local"

- name: Wait for all hosts configured
  hosts: all
  serial: '{{ serial|default("0") }}'
  gather_facts: false
  tasks:
    - name: facts
      set_fact:
        ansible_connection_is_local: '{{ lookup("env","ANSIBLE_CONNECTION")| default(local) }}'

    - name: 'Wait until the string "FINISH: INSTANCE CONFIGURED" is in /var/log/cloud-init-output.log'
      wait_for:
        path: /var/log/cloud-init-output.log
        search_regex: "^FINISH: INSTANCE CONFIGURED$"
      register: instance_configured_check
      until: instance_configured_check|success
      delay: 1  # Check every 1 seconds. Adjust as you like.
      retries: 120  # Retry up to 120 times. Adjust as needed.
      failed_when: instance_configured_check | failed
      when: ansible_connection_is_local != "local"

- name: Gather facts for all hosts
  hosts: all
  serial: '{{ serial|default("0") }}'
  gather_facts: false
  tasks:
    - name: collect facts
      setup:
    - name: set facts
      set_fact:
        service_ntp_enable: '{{ lookup("env","SERVICE_NTP_ENABLE")| default(False) }}'
        service_rsyslog_enable: '{{ lookup("env","SERVICE_RSYSLOG_ENABLE")| default(False) }}'
        service_tinyproxy_enable: '{{ lookup("env","SERVICE_TINYPROXY_ENABLE")| default(False) }}'
        service_openstack_client_enable: '{{ lookup("env","SERVICE_OPENSTACK_CLIENT_ENABLE")| default(False) }}'
        service_docker_compose_enable: '{{ lookup("env","SERVICE_DOCKER_COMPOSE_ENABLE")| default(False) }}'
        service_docker_enable: '{{ lookup("env","SERVICE_DOCKER_ENABLE")| default(False) }}'
  tags: always

- name: Configure docker hosts
  hosts: docker
  gather_facts: false
  serial: '{{ serial|default("0") }}'
  become: true
  roles:
    - role: ntp
      when: service_ntp_enable

    - role: rsyslog
      when: service_rsyslog_enable

    - role: tinyproxy
      when: service_tinyproxy_enable

    - role: openstack-client
      when: service_openstack_client_enable

    - role: docker-compose
      when: service_docker_compose_enable

    - role: docker
      when: service_docker_enable
