---
- name: Configure ntp
  hosts: docker
  roles:
    - role: ntp
      become: true
      when:
        - ansible_env.SERVICE_NTP_ENABLE is defined
        - ansible_env.SERVICE_NTP_ENABLE == "true"

- name: Configure rsyslog
  hosts: docker
  roles:
    - role: rsyslog
      become: true
      when:
        - ansible_env.SERVICE_RSYSLOG_ENABLE is defined
        - ansible_env.SERVICE_RSYSLOG_ENABLE == "true"

- name: Configure tinyproxy
  hosts: docker
  roles:
    - role: tinyproxy
      become: true
      when:
        - ansible_env.SERVICE_TINYPROXY_ENABLE is defined
        - ansible_env.SERVICE_TINYPROXY_ENABLE == "true"

- name: Configure openstack-client
  hosts: docker
  roles:
    - role: openstack-client
      become: true
      when:
        - ansible_env.SERVICE_OPENSTACK_CLIENT_ENABLE is defined
        - ansible_env.SERVICE_OPENSTACK_CLIENT_ENABLE == "true"

- name: Configure docker-compose
  hosts: docker
  roles:
    - role: docker-compose
      become: true
      when:
        - ansible_env.SERVICE_DOCKER_COMPOSE_ENABLE is defined
        - ansible_env.SERVICE_DOCKER_COMPOSE_ENABLE == "true"

- name: Configure docker
  hosts: docker
  roles:
    - role: docker
      become: true
      when:
        - ansible_env.SERVICE_DOCKER_ENABLE is defined
        - ansible_env.SERVICE_DOCKER_ENABLE == "true"
